CREATE TABLE tbl_readbook(
R_SEQ	NUMBER		PRIMARY KEY,
R_BOOK_SEQ	NUMBER	NOT NULL,	
R_DATE	VARCHAR2(10),		
R_STIME	VARCHAR2(10),		
R_ETIME	VARCHAR2(10),		
R_COMMENT	nVARCHAR2(2000)		
);

CREATE SEQUENCE SEQ_READBOOK
START WITH 1 INCREMENT BY 1;


SELECT * FROM tbl_readbook;

CREATE TABLE tbl_navimember(
n_userid	VARCHAR2(30)		PRIMARY KEY,
n_password	nVARCHAR2(255)	NOT NULL,	
n_email	VARCHAR2(125)	NOT NULL,	
n_roll	nVARCHAR2(20)		
);